#Workflow Name
name: PR-IaC(Bicep)

on:
  pull_request:
    branches:
      - main
    paths:
      - "iac/bicep/**"
  # For Manual trigger
  workflow_dispatch:
jobs:
  validation_job:
    name: "Validation Job for Bicep Infra 1"
    runs-on: ubuntu-latest
    steps:
    
    #Checkout Code
    - name: Checkout
      uses: actions/checkout@v2
      
    # Get RESOURCES_PREFIX based on the repo name
    - name: Get repo name
      # actions/github-script@v6 is breaking change which is node16
      uses: actions/github-script@v5
      id: resources_prefix
      with:
          result-encoding: string
          script: return context.repo.repo.toLowerCase()
    # Usage for current job: ${{ steps.resources_prefix.outputs.result }}
    
    # Login to Azure
    - name: Azure Login
      uses: Azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    # Lint - Bicep Check for Syntax error
    - name: Lint Bicep Error Check
      uses: azure/CLI@v1
      with:
        # azcliversion: 2.30.0
        inlineScript: |
          az bicep build --file ./iac/bicep/main.bicep
    # Bicep Validate
    - name: Bicep Check
      uses: azure/CLI@v1
      with:
        # azcliversion: 2.30.0
        inlineScript: |
          az deployment sub validate \
            --name ${{ github.run.id }} \
            --parameters resourcesPrefix="${{ steps.resources_prefix.outputs.result }}" \
            --template-file ./iac/bicep/main.bicep \
            --location ${{ secrets.LOCATION }}
           az logout
